# Font
font_family      Iosevka Nerd Font Mono
font_size        14.0

# Padding
window_padding_width 30

# Transparency
background_opacity 0.65

# Undercurl
undercurl_style thin-sparse

# Colors (Hacker Green)
background #000000
foreground #00ff66
cursor #39ff14
cursor_text_color #000000

color0  #05150a
color1  #39ff14
color2  #00ff66
color3  #a6ff00
color4  #00ffd5
color5  #00aa44
color6  #00ffaa
color7  #d0ffd0

color8  #103015
color9  #39ff14
color10 #55ff88
color11 #d4ff7f
color12 #80ffe9
color13 #33cc77
color14 #80ffd5
color15 #f0fff0

# Scrollback keybindings
map alt+k scroll_line_up
map alt+j scroll_line_down
map alt+u scroll_line_up 10
map alt+d scroll_line_down 10
map alt+b scroll_page_up
map alt+f scroll_page_down
map alt+g scroll_home
map alt+shift+g scroll_end
