# Font
font_family      Iosevka Nerd Font Mono
font_size        14.0

# Padding
window_padding_width 30

# Transparency
background_opacity 0.65

# Undercurl
undercurl_style thin-sparse

# Colors (Tokyo Night)
background #000000
foreground #c0caf5

color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Scrollback keybindings
map alt+k scroll_line_up
map alt+j scroll_line_down
map alt+u scroll_line_up 10
map alt+d scroll_line_down 10
map alt+b scroll_page_up
map alt+f scroll_page_down
map alt+g scroll_home
map alt+shift+g scroll_end
