format = "   $directory$git_branch$git_status$character"

[directory]
style = ""
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = ""

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = ""

[character]
success_symbol = "[❯]()"
error_symbol = "[❯]()"
