# basic apps
$term = alacritty
$filemgr = thunar
$browser = brave
$code = neovim

# Keybinds
$termkb = Super, Return
$filemgrkb = Super, E
$browserkb = Super, W
$kbWindowFullscreen = Super, F

# input
$sensitivity = 0.3
