include-file = $HOME/.config/polybar/colors.ini

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/main]
monitor =
width = 100%
height = 32
offset-x = 0
offset-y = 0
bottom = false
fixed-center = true

; colors.ini の [color] セクションを参照
background = ${color.background}
foreground = ${color.foreground}

radius = 0.0
line-size = 2
border-size = 0
padding-left = 1
padding-right = 1

module-margin = 1

font-0 = "JetBrainsMono Nerd Font:size=11;3"
font-1 = "JetBrainsMono Nerd Font:style=Bold:size=12;3"

; --- 配置: date(左) / i3(左) / title(左) --- ram,cpu(右) ---
modules-left = date  i3  title
modules-center = cava
modules-right = ram  cpu  backlight  pulseaudio  battery  tray

; 区切り線に colors.ini の sep を使用
separator = "|"
separator-foreground = ${color.sep}

wm-name = i3
enable-ipc = true
cursor-click = pointer

; --- 各モジュールの定義 ---



[module/s]
type = custom/text
format = " "

[module/tray]
type = internal/tray
tray-padding = 2px
tray-spacing = 8px
tray-size = 65%
tray-background = ${color.background}


[module/cava]
type = custom/script
tail = true
exec = $HOME/.config/polybar/scripts/cava.sh
format = <label>
format-font = 5
label = %output%

[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
label-muted = 󰟎 MUTE
label-muted-foreground = ${color.red}
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾
ramp-volume-foreground = ${color.blue}

[module/backlight]
type = internal/backlight
card = intel_backlight
format = <ramp> <label>
label = %percentage%%
ramp-0 = "󱩎 "
ramp-1 = "󱩏 "
ramp-2 = "󱩐 "
ramp-3 = "󱩑 "
ramp-4 = "󱩒 "
ramp-foreground = ${color.yellow}
enable-scroll = true
[module/battery]
type = internal/battery
full-at = 98
battery = BAT1
adapter = ADP0
format-charging = <label-charging>
format-charging-prefix = "󰂄 "
format-charging-prefix-foreground = ${color.green}
format-discharging = <label-discharging>
format-discharging-prefix = "󰁹 "
format-discharging-prefix-foreground = ${color.blue}
label-charging = "%percentage%%"
label-discharging = "%percentage%%"

[module/cpu]
type = internal/cpu
interval = 1
format-prefix = "CPU "
format-prefix-foreground = ${color.green}
label = "%percentage%%"

[module/ram]
type = internal/memory
interval = 1
format-prefix = "RAM "
format-prefix-foreground = ${color.purple}
label = "%gb_used%"

[module/date]
type = internal/date
interval = 1
date = %Y-%m-%d %a
time = %H:%M
label = %date% %time%

[module/i3]
type = internal/i3
pin-workspaces = true
format = <label-state> <label-mode>
label-focused = %index%
label-focused-foreground = ${color.green}
label-focused-underline = ${color.green}
label-focused-padding = 1
label-unfocused = %index%
label-unfocused-padding = 1
label-urgent = %index%
label-urgent-foreground = ${color.red}
label-urgent-padding = 1

[module/title]
type = internal/xwindow
format = <label>
label = %class%
label-maxlen = 20
label-empty = Desktop
label-empty-foreground = ${color.sep}
