$background = rgb(11131a)
$foreground = rgb(e1e2eb)
$primary = rgb(adc6ff)
$secondary = rgb(b1c6f7)
$tertiary = rgb(ffb780)
$error = rgb(ffb4ab)

$active_border = rgb(adc6ff)
$inactive_border = rgb(363940)